null:
    resource: "@NullBundle/Resources/config/routing/default.yml"
    prefix:   /

NullBundle_event:
    resource: "@NullBundle/Resources/config/routing/event.yml"
    prefix:   /event

NullBundle_event_annotation:
    resource: "@NullBundle/Controller"
    prefix:   /event
    type:     annotation

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
